source "https://rubygems.org"

ruby "3.4.5"
gem "jekyll"
gem "minima"
gem "github-pages",  group: :jekyll_plugins

group :jekyll_plugins do
  gem "jekyll-feed"
  gem "jekyll-seo-tag"
  gem "jekyll-paginate"
  gem "jekyll-sitemap"
end

gem "tzinfo"
gem "tzinfo-data"
gem "wdm", :platforms => [:mingw, :x64_mingw, :mswin]

gem "webrick"